{% set name = "chroman" %}
{% set version = "0.0.25" %}
 

package:
  name: chroman
  version: 0.1

source:
  path: ../

build:
  noarch: python
  number: 1
  entry_points:
    - install_chromium = chroman.command:install_chromium
    - find_chromium = chroman.command:find_chromium
    - clean_chromium = chroman.command:clean_chromium
    - print_chromium = chroman.command:print_chromium

  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - click
    - appdirs

test:
  imports:
    - chroman

about:
  home: https://github.com/eoas-ubc/trio-chrome
  license: MIT
  license_family: BSD
  license_file: LICENSE
  summary: "Headless chrome/chromium automation"
  doc_url: https://github.com/eoas-ubc/trio-chrome
  dev_url: https://github.com/eoas-ubc/trio-chrome

extra:
  recipe-maintainers:
    - phaustin
